"""Project-specific metadata for the local runtime."""

from agents.models import ProjectSpec

PROJECT_CONTEXT = {'repo_name': 'Synthesis-Ampersend',
 'project_name': 'Ampersend Settlement Bus',
 'track': 'Ampersend',
 'pitch': 'A settlement bus that packages intent metadata together with payments and '
          'routing instructions so downstream tracks can share one transport layer.',
 'idea_titles': ['Payment + Intent Routing Bus',
                 'Lido MCP Settlement Spine',
                 'Delegated Execution Transport'],
 'architecture_summary': 'A transport layer packages intent metadata together with '
                         'settlement instructions so downstream tracks can reuse one '
                         'message bus. The contract emits intent receipts and '
                         'settlement checkpoints, while Python adapters stage routing '
                         'plans for live payment infrastructure.',
 'overlap_targets': ['Lido MCP Server',
                     'Uniswap Agentic Finance',
                     'MetaMask Delegations',
                     'Filecoin',
                     'OpenServ',
                     'ERC-8004 Receipts'],
 'primary_contract_name': 'SettlementBus',
 'primary_python_module': 'ampersend_bus',
 'category': 'transport',
 'daily_budget_usd': 114,
 'per_action_budget_usd': 28,
 'cooldown_seconds': 900,
 'discovery_inputs': [{'name': 'intent_queue',
                       'description': 'Settlement-bound messages and routing intents.'},
                      {'name': 'counterparties',
                       'description': 'Target services and payment endpoints.'},
                      {'name': 'delivery_policy',
                       'description': 'Allowlists, retries, and signed envelopes.'},
                      {'name': 'receipts',
                       'description': 'Transport proofs and submission notes.'}],
 'live_demo_steps': ['Copy .env.example to .env and fill the required keys.',
                     'Deploy the contract with forge script script/Deploy.s.sol '
                     '--broadcast for SettlementBus.',
                     'Run python3 scripts/run_agent.py to produce a dry run for '
                     'ampersend_bus.',
                     'Set LIVE_MODE=true and rerun python3 scripts/run_agent.py with '
                     'real credentials.',
                     'Run python3 scripts/render_submission.py and attach TxIDs plus '
                     'repo links.'],
 'partners': [{'name': 'Ampersend',
               'docs_url': 'https://docs.ampersend.ai/',
               'env_vars': ['AMPERSEND_API_KEY', 'AMPERSEND_PAYMENT_URL'],
               'endpoint_env': 'AMPERSEND_PAYMENT_URL',
               'action_kind': 'rest_json',
               'purpose': 'Bundle payment and transport metadata for downstream '
                          'agents.'},
              {'name': 'Lido MCP Server',
               'docs_url': 'https://docs.lido.fi/',
               'env_vars': ['RPC_URL'],
               'endpoint_env': '',
               'action_kind': 'contract_call',
               'purpose': 'Call MCP-style Lido verbs behind policy envelopes.'},
              {'name': 'Uniswap',
               'docs_url': 'https://developers.uniswap.org/',
               'env_vars': ['UNISWAP_API_KEY', 'UNISWAP_QUOTE_URL'],
               'endpoint_env': 'UNISWAP_QUOTE_URL',
               'action_kind': 'rest_json',
               'purpose': 'Quote swaps and bounded liquidity moves.'},
              {'name': 'MetaMask Delegations',
               'docs_url': 'https://docs.metamask.io/delegation-toolkit/',
               'env_vars': ['RPC_URL'],
               'endpoint_env': '',
               'action_kind': 'contract_call',
               'purpose': 'Enforce delegation scopes, expiries, and intent envelopes.'},
              {'name': 'Filecoin',
               'docs_url': 'https://docs.filecoin.cloud/',
               'env_vars': ['FILECOIN_API_TOKEN', 'FILECOIN_UPLOAD_URL'],
               'endpoint_env': 'FILECOIN_UPLOAD_URL',
               'action_kind': 'file_upload',
               'purpose': 'Persist proofs, logs, and evidence bundles offchain.'},
              {'name': 'OpenServ',
               'docs_url': 'https://docs.openserv.ai/',
               'env_vars': ['OPENSERV_API_KEY', 'OPENSERV_AGENT_URL'],
               'endpoint_env': 'OPENSERV_AGENT_URL',
               'action_kind': 'rest_json',
               'purpose': 'Dispatch jobs and expose swarm service endpoints.'},
              {'name': 'ERC-8004 Receipts',
               'docs_url': 'https://eips.ethereum.org/EIPS/eip-8004',
               'env_vars': ['RPC_URL'],
               'endpoint_env': '',
               'action_kind': 'contract_call',
               'purpose': 'Anchor identity, task receipts, and reputation updates.'}],
 'actions': [{'id': 'ampersend_settlement_bundle',
              'target': 'ampersend',
              'purpose': 'Use Ampersend for a bounded action in this repo.',
              'partner': 'Ampersend',
              'action_kind': 'rest_json',
              'max_amount_usd': 25,
              'priority': 100,
              'sensitivity': 'medium',
              'notes': ['Call Ampersend only after a dry-run artifact exists.',
                        'Use https://docs.ampersend.ai/ for credential setup.']},
             {'id': 'lido_mcp_server_mcp_call',
              'target': 'lido_mcp_server',
              'purpose': 'Use Lido MCP Server for a bounded action in this repo.',
              'partner': 'Lido MCP Server',
              'action_kind': 'contract_call',
              'max_amount_usd': 2,
              'priority': 95,
              'sensitivity': 'medium',
              'notes': ['Call Lido MCP Server only after a dry-run artifact exists.',
                        'Use https://docs.lido.fi/ for credential setup.']},
             {'id': 'uniswap_quote_route',
              'target': 'uniswap',
              'purpose': 'Use Uniswap for a bounded action in this repo.',
              'partner': 'Uniswap',
              'action_kind': 'rest_json',
              'max_amount_usd': 220,
              'priority': 90,
              'sensitivity': 'medium',
              'notes': ['Call Uniswap only after a dry-run artifact exists.',
                        'Use https://developers.uniswap.org/ for credential setup.']},
             {'id': 'metamask_delegations_delegate_scope',
              'target': 'metamask_delegations',
              'purpose': 'Use MetaMask Delegations for a bounded action in this repo.',
              'partner': 'MetaMask Delegations',
              'action_kind': 'contract_call',
              'max_amount_usd': 2,
              'priority': 85,
              'sensitivity': 'high',
              'notes': ['Call MetaMask Delegations only after a dry-run artifact '
                        'exists.',
                        'Use https://docs.metamask.io/delegation-toolkit/ for '
                        'credential setup.']},
             {'id': 'filecoin_proof_store',
              'target': 'filecoin',
              'purpose': 'Use Filecoin for a bounded action in this repo.',
              'partner': 'Filecoin',
              'action_kind': 'file_upload',
              'max_amount_usd': 20,
              'priority': 80,
              'sensitivity': 'medium',
              'notes': ['Call Filecoin only after a dry-run artifact exists.',
                        'Use https://docs.filecoin.cloud/ for credential setup.']},
             {'id': 'openserv_job_dispatch',
              'target': 'openserv',
              'purpose': 'Use OpenServ for a bounded action in this repo.',
              'partner': 'OpenServ',
              'action_kind': 'rest_json',
              'max_amount_usd': 10,
              'priority': 75,
              'sensitivity': 'medium',
              'notes': ['Call OpenServ only after a dry-run artifact exists.',
                        'Use https://docs.openserv.ai/ for credential setup.']},
             {'id': 'erc_8004_receipts_receipt_anchor',
              'target': 'erc_8004_receipts',
              'purpose': 'Use ERC-8004 Receipts for a bounded action in this repo.',
              'partner': 'ERC-8004 Receipts',
              'action_kind': 'contract_call',
              'max_amount_usd': 1,
              'priority': 70,
              'sensitivity': 'medium',
              'notes': ['Call ERC-8004 Receipts only after a dry-run artifact exists.',
                        'Use https://eips.ethereum.org/EIPS/eip-8004 for credential '
                        'setup.']}]}


def build_project_spec() -> ProjectSpec:
    """Return the repository-specific project metadata."""
    return ProjectSpec.from_dict(PROJECT_CONTEXT)
